// src/services/mockPlayers.js

export const COMPETITION_PLAYERS = {
  PL: [
    // Goalkeepers
    {
      id: 101,
      name: "David Raya",
      team: "Arsenal",
      goals: 0,
      assists: 0,
      minutes: 450,
      yellowCards: 0,
      points: 35,
      position: "GK",
      category: "GOALKEEPERS",
      customStats: {
        cleanSheets: 3,
        saves: 16,
        savePercentage: "84.2%",
        goalsConceded: 3,
      },
    },
    {
      id: 102,
      name: "Alisson Becker",
      team: "Liverpool",
      goals: 0,
      assists: 0,
      minutes: 450,
      yellowCards: 0,
      points: 32,
      position: "GK",
      category: "GOALKEEPERS",
      customStats: {
        cleanSheets: 2,
        saves: 18,
        savePercentage: "81.8%",
        goalsConceded: 4,
      },
    },

    // Centrebacks
    {
      id: 103,
      name: "William Saliba",
      team: "Arsenal",
      goals: 1,
      assists: 0,
      minutes: 450,
      yellowCards: 0,
      points: 28,
      position: "CB",
      category: "CENTREBACKS",
      customStats: {
        aerialDuelsWon: "78%",
        tacklesWon: 12,
        interceptions: 9,
        cleanSheets: 3,
      },
    },
    {
      id: 104,
      name: "Virgil van Dijk",
      team: "Liverpool",
      goals: 0,
      assists: 1,
      minutes: 450,
      yellowCards: 1,
      points: 25,
      position: "CB",
      category: "CENTREBACKS",
      customStats: {
        aerialDuelsWon: "85%",
        tacklesWon: 10,
        interceptions: 11,
        cleanSheets: 2,
      },
    },

    // Fullbacks
    {
      id: 105,
      name: "Josko Gvardiol",
      team: "Manchester City",
      goals: 1,
      assists: 1,
      minutes: 420,
      yellowCards: 1,
      points: 30,
      position: "FB",
      category: "FULLBACKS",
      customStats: {
        crossesCompleted: 8,
        keyPasses: 7,
        dribblesSuccess: "65%",
        tacklesWon: 14,
      },
    },
    {
      id: 106,
      name: "Trent Alexander-Arnold",
      team: "Liverpool",
      goals: 0,
      assists: 2,
      minutes: 400,
      yellowCards: 1,
      points: 27,
      position: "FB",
      category: "FULLBACKS",
      customStats: {
        crossesCompleted: 15,
        keyPasses: 14,
        dribblesSuccess: "60%",
        tacklesWon: 9,
      },
    },

    // Midfielders
    {
      id: 107,
      name: "Cole Palmer",
      team: "Chelsea",
      goals: 4,
      assists: 3,
      minutes: 450,
      yellowCards: 1,
      points: 48,
      position: "MF",
      category: "MIDFIELDERS",
      customStats: {
        keyPasses: 18,
        passAccuracy: "88.5%",
        progressiveCarries: 22,
        shotCreatingActions: 27,
      },
    },
    {
      id: 108,
      name: "Kevin De Bruyne",
      team: "Manchester City",
      goals: 2,
      assists: 4,
      minutes: 380,
      yellowCards: 0,
      points: 42,
      position: "MF",
      category: "MIDFIELDERS",
      customStats: {
        keyPasses: 21,
        passAccuracy: "86.0%",
        progressiveCarries: 16,
        shotCreatingActions: 31,
      },
    },

    // Wingers
    {
      id: 109,
      name: "Bukayo Saka",
      team: "Arsenal",
      goals: 3,
      assists: 3,
      minutes: 430,
      yellowCards: 0,
      points: 44,
      position: "WG",
      category: "WINGERS",
      customStats: {
        successfulDribbles: 17,
        shotsOnTarget: 9,
        xG: 3.2,
        chancesCreated: 19,
      },
    },
    {
      id: 110,
      name: "Mohamed Salah",
      team: "Liverpool",
      goals: 3,
      assists: 2,
      minutes: 440,
      yellowCards: 0,
      points: 41,
      position: "WG",
      category: "WINGERS",
      customStats: {
        successfulDribbles: 14,
        shotsOnTarget: 12,
        xG: 3.8,
        chancesCreated: 15,
      },
    },

    // Strikers
    {
      id: 111,
      name: "Erling Haaland",
      team: "Manchester City",
      goals: 7,
      assists: 1,
      minutes: 450,
      yellowCards: 0,
      points: 55,
      position: "FW",
      category: "STRIKERS",
      customStats: {
        shotsOnTarget: 15,
        conversionRate: "46.7%",
        xG: 6.4,
        touchesInBox: 42,
      },
    },
    {
      id: 112,
      name: "Ollie Watkins",
      team: "Aston Villa",
      goals: 3,
      assists: 2,
      minutes: 410,
      yellowCards: 1,
      points: 38,
      position: "FW",
      category: "STRIKERS",
      customStats: {
        shotsOnTarget: 10,
        conversionRate: "30.0%",
        xG: 3.5,
        touchesInBox: 31,
      },
    },
  ],

  PD: [
    // Goalkeepers
    {
      id: 201,
      name: "Thibaut Courtois",
      team: "Real Madrid",
      goals: 0,
      assists: 0,
      minutes: 450,
      yellowCards: 0,
      points: 33,
      position: "GK",
      category: "GOALKEEPERS",
      customStats: {
        cleanSheets: 3,
        saves: 14,
        savePercentage: "82.3%",
        goalsConceded: 3,
      },
    },
    {
      id: 202,
      name: "Marc-André ter Stegen",
      team: "Barcelona",
      goals: 0,
      assists: 0,
      minutes: 450,
      yellowCards: 0,
      points: 30,
      position: "GK",
      category: "GOALKEEPERS",
      customStats: {
        cleanSheets: 2,
        saves: 15,
        savePercentage: "79.0%",
        goalsConceded: 4,
      },
    },

    // Centrebacks
    {
      id: 203,
      name: "Antonio Rüdiger",
      team: "Real Madrid",
      goals: 1,
      assists: 0,
      minutes: 450,
      yellowCards: 1,
      points: 27,
      position: "CB",
      category: "CENTREBACKS",
      customStats: {
        aerialDuelsWon: "81%",
        tacklesWon: 13,
        interceptions: 8,
        cleanSheets: 3,
      },
    },
    {
      id: 204,
      name: "Pau Cubarsí",
      team: "Barcelona",
      goals: 0,
      assists: 1,
      minutes: 400,
      yellowCards: 1,
      points: 24,
      position: "CB",
      category: "CENTREBACKS",
      customStats: {
        aerialDuelsWon: "72%",
        tacklesWon: 9,
        interceptions: 12,
        cleanSheets: 2,
      },
    },

    // Fullbacks
    {
      id: 205,
      name: "Dani Carvajal",
      team: "Real Madrid",
      goals: 1,
      assists: 1,
      minutes: 380,
      yellowCards: 2,
      points: 28,
      position: "FB",
      category: "FULLBACKS",
      customStats: {
        crossesCompleted: 6,
        keyPasses: 5,
        dribblesSuccess: "62%",
        tacklesWon: 15,
      },
    },
    {
      id: 206,
      name: "Jules Koundé",
      team: "Barcelona",
      goals: 0,
      assists: 2,
      minutes: 450,
      yellowCards: 0,
      points: 29,
      position: "FB",
      category: "FULLBACKS",
      customStats: {
        crossesCompleted: 9,
        keyPasses: 8,
        dribblesSuccess: "68%",
        tacklesWon: 13,
      },
    },

    // Midfielders
    {
      id: 207,
      name: "Jude Bellingham",
      team: "Real Madrid",
      goals: 3,
      assists: 2,
      minutes: 420,
      yellowCards: 1,
      points: 41,
      position: "MF",
      category: "MIDFIELDERS",
      customStats: {
        keyPasses: 15,
        passAccuracy: "89.0%",
        progressiveCarries: 25,
        shotCreatingActions: 24,
      },
    },
    {
      id: 208,
      name: "Pedri",
      team: "Barcelona",
      goals: 2,
      assists: 3,
      minutes: 410,
      yellowCards: 0,
      points: 39,
      position: "MF",
      category: "MIDFIELDERS",
      customStats: {
        keyPasses: 17,
        passAccuracy: "92.1%",
        progressiveCarries: 20,
        shotCreatingActions: 26,
      },
    },

    // Wingers
    {
      id: 209,
      name: "Vinicius Junior",
      team: "Real Madrid",
      goals: 4,
      assists: 2,
      minutes: 430,
      yellowCards: 1,
      points: 45,
      position: "WG",
      category: "WINGERS",
      customStats: {
        successfulDribbles: 22,
        shotsOnTarget: 11,
        xG: 4.1,
        chancesCreated: 18,
      },
    },
    {
      id: 210,
      name: "Lamine Yamal",
      team: "Barcelona",
      goals: 2,
      assists: 4,
      minutes: 440,
      yellowCards: 0,
      points: 43,
      position: "WG",
      category: "WINGERS",
      customStats: {
        successfulDribbles: 20,
        shotsOnTarget: 8,
        xG: 2.5,
        chancesCreated: 23,
      },
    },

    // Strikers
    {
      id: 211,
      name: "Kylian Mbappé",
      team: "Real Madrid",
      goals: 5,
      assists: 1,
      minutes: 450,
      yellowCards: 0,
      points: 49,
      position: "FW",
      category: "STRIKERS",
      customStats: {
        shotsOnTarget: 16,
        conversionRate: "38.5%",
        xG: 5.2,
        touchesInBox: 45,
      },
    },
    {
      id: 212,
      name: "Robert Lewandowski",
      team: "Barcelona",
      goals: 4,
      assists: 1,
      minutes: 420,
      yellowCards: 0,
      points: 42,
      position: "FW",
      category: "STRIKERS",
      customStats: {
        shotsOnTarget: 13,
        conversionRate: "36.4%",
        xG: 4.3,
        touchesInBox: 38,
      },
    },
  ],

  SA: [
    // Goalkeepers
    {
      id: 301,
      name: "Yann Sommer",
      team: "Inter Milan",
      goals: 0,
      assists: 0,
      minutes: 450,
      yellowCards: 0,
      points: 34,
      position: "GK",
      category: "GOALKEEPERS",
      customStats: {
        cleanSheets: 4,
        saves: 13,
        savePercentage: "86.6%",
        goalsConceded: 2,
      },
    },
    {
      id: 302,
      name: "Mike Maignan",
      team: "AC Milan",
      goals: 0,
      assists: 0,
      minutes: 450,
      yellowCards: 0,
      points: 31,
      position: "GK",
      category: "GOALKEEPERS",
      customStats: {
        cleanSheets: 2,
        saves: 17,
        savePercentage: "80.9%",
        goalsConceded: 4,
      },
    },

    // Centrebacks
    {
      id: 303,
      name: "Alessandro Bastoni",
      team: "Inter Milan",
      goals: 0,
      assists: 1,
      minutes: 450,
      yellowCards: 0,
      points: 26,
      position: "CB",
      category: "CENTREBACKS",
      customStats: {
        aerialDuelsWon: "75%",
        tacklesWon: 11,
        interceptions: 13,
        cleanSheets: 4,
      },
    },
    {
      id: 304,
      name: "Gleison Bremer",
      team: "Juventus",
      goals: 1,
      assists: 0,
      minutes: 450,
      yellowCards: 1,
      points: 27,
      position: "CB",
      category: "CENTREBACKS",
      customStats: {
        aerialDuelsWon: "83%",
        tacklesWon: 15,
        interceptions: 10,
        cleanSheets: 3,
      },
    },

    // Fullbacks
    {
      id: 305,
      name: "Federico Dimarco",
      team: "Inter Milan",
      goals: 1,
      assists: 2,
      minutes: 400,
      yellowCards: 0,
      points: 32,
      position: "FB",
      category: "FULLBACKS",
      customStats: {
        crossesCompleted: 12,
        keyPasses: 11,
        dribblesSuccess: "58%",
        tacklesWon: 10,
      },
    },
    {
      id: 306,
      name: "Theo Hernández",
      team: "AC Milan",
      goals: 1,
      assists: 1,
      minutes: 420,
      yellowCards: 1,
      points: 29,
      position: "FB",
      category: "FULLBACKS",
      customStats: {
        crossesCompleted: 9,
        keyPasses: 9,
        dribblesSuccess: "71%",
        tacklesWon: 12,
      },
    },

    // Midfielders
    {
      id: 307,
      name: "Hakan Çalhanoğlu",
      team: "Inter Milan",
      goals: 3,
      assists: 1,
      minutes: 420,
      yellowCards: 1,
      points: 38,
      position: "MF",
      category: "MIDFIELDERS",
      customStats: {
        keyPasses: 16,
        passAccuracy: "91.2%",
        progressiveCarries: 14,
        shotCreatingActions: 22,
      },
    },
    {
      id: 308,
      name: "Teun Koopmeiners",
      team: "Juventus",
      goals: 2,
      assists: 2,
      minutes: 400,
      yellowCards: 0,
      points: 36,
      position: "MF",
      category: "MIDFIELDERS",
      customStats: {
        keyPasses: 14,
        passAccuracy: "87.5%",
        progressiveCarries: 18,
        shotCreatingActions: 20,
      },
    },

    // Wingers
    {
      id: 309,
      name: "Rafael Leão",
      team: "AC Milan",
      goals: 2,
      assists: 2,
      minutes: 410,
      yellowCards: 1,
      points: 35,
      position: "WG",
      category: "WINGERS",
      customStats: {
        successfulDribbles: 19,
        shotsOnTarget: 8,
        xG: 2.4,
        chancesCreated: 14,
      },
    },
    {
      id: 310,
      name: "Christian Pulisic",
      team: "AC Milan",
      goals: 3,
      assists: 1,
      minutes: 430,
      yellowCards: 0,
      points: 37,
      position: "WG",
      category: "WINGERS",
      customStats: {
        successfulDribbles: 15,
        shotsOnTarget: 10,
        xG: 2.9,
        chancesCreated: 16,
      },
    },

    // Strikers
    {
      id: 311,
      name: "Lautaro Martínez",
      team: "Inter Milan",
      goals: 4,
      assists: 1,
      minutes: 430,
      yellowCards: 1,
      points: 41,
      position: "FW",
      category: "STRIKERS",
      customStats: {
        shotsOnTarget: 14,
        conversionRate: "33.3%",
        xG: 4.2,
        touchesInBox: 39,
      },
    },
    {
      id: 312,
      name: "Dusan Vlahovic",
      team: "Juventus",
      goals: 4,
      assists: 0,
      minutes: 420,
      yellowCards: 1,
      points: 39,
      position: "FW",
      category: "STRIKERS",
      customStats: {
        shotsOnTarget: 12,
        conversionRate: "36.4%",
        xG: 4.0,
        touchesInBox: 34,
      },
    },
  ],

  BL1: [
    // Goalkeepers
    {
      id: 401,
      name: "Manuel Neuer",
      team: "Bayern Munich",
      goals: 0,
      assists: 0,
      minutes: 400,
      yellowCards: 0,
      points: 29,
      position: "GK",
      category: "GOALKEEPERS",
      customStats: {
        cleanSheets: 2,
        saves: 11,
        savePercentage: "78.5%",
        goalsConceded: 3,
      },
    },
    {
      id: 402,
      name: "Gregor Kobel",
      team: "Borussia Dortmund",
      goals: 0,
      assists: 0,
      minutes: 400,
      yellowCards: 0,
      points: 28,
      position: "GK",
      category: "GOALKEEPERS",
      customStats: {
        cleanSheets: 2,
        saves: 15,
        savePercentage: "79.0%",
        goalsConceded: 4,
      },
    },

    // Centrebacks
    {
      id: 403,
      name: "Jonathan Tah",
      team: "Bayer Leverkusen",
      goals: 1,
      assists: 0,
      minutes: 400,
      yellowCards: 1,
      points: 25,
      position: "CB",
      category: "CENTREBACKS",
      customStats: {
        aerialDuelsWon: "80%",
        tacklesWon: 10,
        interceptions: 8,
        cleanSheets: 2,
      },
    },
    {
      id: 404,
      name: "Dayot Upamecano",
      team: "Bayern Munich",
      goals: 0,
      assists: 0,
      minutes: 400,
      yellowCards: 1,
      points: 22,
      position: "CB",
      category: "CENTREBACKS",
      customStats: {
        aerialDuelsWon: "76%",
        tacklesWon: 9,
        interceptions: 9,
        cleanSheets: 2,
      },
    },

    // Fullbacks
    {
      id: 405,
      name: "Alejandro Grimaldo",
      team: "Bayer Leverkusen",
      goals: 2,
      assists: 3,
      minutes: 400,
      yellowCards: 0,
      points: 40,
      position: "FB",
      category: "FULLBACKS",
      customStats: {
        crossesCompleted: 16,
        keyPasses: 15,
        dribblesSuccess: "67%",
        tacklesWon: 11,
      },
    },
    {
      id: 406,
      name: "Jeremie Frimpong",
      team: "Bayer Leverkusen",
      goals: 2,
      assists: 2,
      minutes: 390,
      yellowCards: 1,
      points: 37,
      position: "FB",
      category: "FULLBACKS",
      customStats: {
        crossesCompleted: 11,
        keyPasses: 12,
        dribblesSuccess: "75%",
        tacklesWon: 9,
      },
    },

    // Midfielders
    {
      id: 407,
      name: "Florian Wirtz",
      team: "Bayer Leverkusen",
      goals: 3,
      assists: 3,
      minutes: 400,
      yellowCards: 0,
      points: 45,
      position: "MF",
      category: "MIDFIELDERS",
      customStats: {
        keyPasses: 19,
        passAccuracy: "89.5%",
        progressiveCarries: 26,
        shotCreatingActions: 29,
      },
    },
    {
      id: 408,
      name: "Jamal Musiala",
      team: "Bayern Munich",
      goals: 3,
      assists: 2,
      minutes: 390,
      yellowCards: 0,
      points: 42,
      position: "MF",
      category: "MIDFIELDERS",
      customStats: {
        keyPasses: 16,
        passAccuracy: "88.0%",
        progressiveCarries: 28,
        shotCreatingActions: 27,
      },
    },

    // Wingers
    {
      id: 409,
      name: "Michael Olise",
      team: "Bayern Munich",
      goals: 2,
      assists: 4,
      minutes: 380,
      yellowCards: 0,
      points: 40,
      position: "WG",
      category: "WINGERS",
      customStats: {
        successfulDribbles: 16,
        shotsOnTarget: 9,
        xG: 2.3,
        chancesCreated: 21,
      },
    },
    {
      id: 410,
      name: "Serge Gnabry",
      team: "Bayern Munich",
      goals: 2,
      assists: 2,
      minutes: 350,
      yellowCards: 0,
      points: 33,
      position: "WG",
      category: "WINGERS",
      customStats: {
        successfulDribbles: 12,
        shotsOnTarget: 7,
        xG: 2.1,
        chancesCreated: 13,
      },
    },

    // Strikers
    {
      id: 411,
      name: "Harry Kane",
      team: "Bayern Munich",
      goals: 6,
      assists: 2,
      minutes: 400,
      yellowCards: 0,
      points: 52,
      position: "FW",
      category: "STRIKERS",
      customStats: {
        shotsOnTarget: 17,
        conversionRate: "40.0%",
        xG: 5.9,
        touchesInBox: 40,
      },
    },
    {
      id: 412,
      name: "Victor Boniface",
      team: "Bayer Leverkusen",
      goals: 4,
      assists: 1,
      minutes: 370,
      yellowCards: 1,
      points: 39,
      position: "FW",
      category: "STRIKERS",
      customStats: {
        shotsOnTarget: 11,
        conversionRate: "36.4%",
        xG: 4.1,
        touchesInBox: 33,
      },
    },
  ],

  FL1: [
    // Goalkeepers
    {
      id: 501,
      name: "Gianluigi Donnarumma",
      team: "Paris Saint-Germain",
      goals: 0,
      assists: 0,
      minutes: 400,
      yellowCards: 0,
      points: 31,
      position: "GK",
      category: "GOALKEEPERS",
      customStats: {
        cleanSheets: 3,
        saves: 12,
        savePercentage: "80.0%",
        goalsConceded: 3,
      },
    },
    {
      id: 502,
      name: "Lucas Chevalier",
      team: "Lille",
      goals: 0,
      assists: 0,
      minutes: 400,
      yellowCards: 0,
      points: 29,
      position: "GK",
      category: "GOALKEEPERS",
      customStats: {
        cleanSheets: 2,
        saves: 14,
        savePercentage: "77.7%",
        goalsConceded: 4,
      },
    },

    // Centrebacks
    {
      id: 503,
      name: "Marquinhos",
      team: "Paris Saint-Germain",
      goals: 0,
      assists: 0,
      minutes: 400,
      yellowCards: 0,
      points: 24,
      position: "CB",
      category: "CENTREBACKS",
      customStats: {
        aerialDuelsWon: "74%",
        tacklesWon: 8,
        interceptions: 10,
        cleanSheets: 3,
      },
    },
    {
      id: 504,
      name: "Willian Pacho",
      team: "Paris Saint-Germain",
      goals: 0,
      assists: 1,
      minutes: 400,
      yellowCards: 1,
      points: 25,
      position: "CB",
      category: "CENTREBACKS",
      customStats: {
        aerialDuelsWon: "77%",
        tacklesWon: 11,
        interceptions: 9,
        cleanSheets: 3,
      },
    },

    // Fullbacks
    {
      id: 505,
      name: "Achraf Hakimi",
      team: "Paris Saint-Germain",
      goals: 2,
      assists: 2,
      minutes: 400,
      yellowCards: 1,
      points: 36,
      position: "FB",
      category: "FULLBACKS",
      customStats: {
        crossesCompleted: 13,
        keyPasses: 12,
        dribblesSuccess: "70%",
        tacklesWon: 12,
      },
    },
    {
      id: 506,
      name: "Nuno Mendes",
      team: "Paris Saint-Germain",
      goals: 1,
      assists: 2,
      minutes: 380,
      yellowCards: 1,
      points: 32,
      position: "FB",
      category: "FULLBACKS",
      customStats: {
        crossesCompleted: 10,
        keyPasses: 10,
        dribblesSuccess: "72%",
        tacklesWon: 11,
      },
    },

    // Midfielders
    {
      id: 507,
      name: "Vitinha",
      team: "Paris Saint-Germain",
      goals: 2,
      assists: 2,
      minutes: 400,
      yellowCards: 0,
      points: 37,
      position: "MF",
      category: "MIDFIELDERS",
      customStats: {
        keyPasses: 15,
        passAccuracy: "93.0%",
        progressiveCarries: 19,
        shotCreatingActions: 23,
      },
    },
    {
      id: 508,
      name: "João Neves",
      team: "Paris Saint-Germain",
      goals: 0,
      assists: 4,
      minutes: 390,
      yellowCards: 1,
      points: 35,
      position: "MF",
      category: "MIDFIELDERS",
      customStats: {
        keyPasses: 14,
        passAccuracy: "91.5%",
        progressiveCarries: 15,
        shotCreatingActions: 21,
      },
    },

    // Wingers
    {
      id: 509,
      name: "Ousmane Dembélé",
      team: "Paris Saint-Germain",
      goals: 3,
      assists: 4,
      minutes: 380,
      yellowCards: 1,
      points: 44,
      position: "WG",
      category: "WINGERS",
      customStats: {
        successfulDribbles: 25,
        shotsOnTarget: 10,
        xG: 3.1,
        chancesCreated: 24,
      },
    },
    {
      id: 510,
      name: "Bradley Barcola",
      team: "Paris Saint-Germain",
      goals: 4,
      assists: 1,
      minutes: 390,
      yellowCards: 0,
      points: 41,
      position: "WG",
      category: "WINGERS",
      customStats: {
        successfulDribbles: 18,
        shotsOnTarget: 11,
        xG: 3.6,
        chancesCreated: 17,
      },
    },

    // Strikers
    {
      id: 511,
      name: "Gonçalo Ramos",
      team: "Paris Saint-Germain",
      goals: 3,
      assists: 1,
      minutes: 300,
      yellowCards: 0,
      points: 32,
      position: "FW",
      category: "STRIKERS",
      customStats: {
        shotsOnTarget: 9,
        conversionRate: "33.3%",
        xG: 2.8,
        touchesInBox: 28,
      },
    },
    {
      id: 512,
      name: "Jonathan David",
      team: "Lille",
      goals: 3,
      assists: 1,
      minutes: 400,
      yellowCards: 0,
      points: 33,
      position: "FW",
      category: "STRIKERS",
      customStats: {
        shotsOnTarget: 10,
        conversionRate: "30.0%",
        xG: 3.2,
        touchesInBox: 30,
      },
    },
  ],
};